apiVersion: v1
kind: Service
metadata:
  name: otel-collector-gateway
  namespace: opentelemetry
  labels:
    app: otel-collector-gateway
    app.kubernetes.io/part-of: observability-learning-lab
spec:
  type: ClusterIP
  selector:
    app: otel-collector-gateway
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: health
      port: 13133
      targetPort: health
    - name: metrics
      port: 8888
      targetPort: metrics
    - name: prom-export
      port: 8889
      targetPort: prom-export
