#!/usr/bin/env bash
# Guest provisioning step 05: kubeadm control-plane initialization.
# Runs only on the control-plane node. Idempotent: never re-runs
# `kubeadm init` if the cluster is already initialized, but always
# regenerates the worker join command/token (they expire) and refreshes
# the exported kubeconfig, both of which are safe to redo.
set -euo pipefail

MODULE_ROOT="/vagrant"
# shellcheck source=../lib/common.sh
source "${MODULE_ROOT}/scripts/lib/common.sh"
# shellcheck source=../lib/validation.sh
source "${MODULE_ROOT}/scripts/lib/validation.sh"

require_root
: "${NODE_NAME:?}"
: "${NODE_ROLE:?}"

if [ "${NODE_ROLE}" != "control-plane" ]; then
  log_info "05-init-control-plane: not the control plane, skipping (${NODE_NAME})."
  exit 0
fi

log_section "05-init-control-plane: kubeadm init (${NODE_NAME})"

export CLUSTER_NAME CONTROL_PLANE_NAME CONTROL_PLANE_IP CONTROL_PLANE_ENDPOINT \
  SERVICE_SUBNET CILIUM_CLUSTER_POOL_CIDR CILIUM_CLUSTER_POOL_MASK_SIZE \
  CRI_SOCKET KUBERNETES_VERSION

if is_control_plane_initialized; then
  log_info "kubeadm already initialized on this node (admin.conf present) — skipping 'kubeadm init'."
else
  render_template "${MODULE_ROOT}/config/kubeadm-config.yaml.tpl" "${RENDERED_DIR}/kubeadm-config.yaml"
  kubeadm init --config "${RENDERED_DIR}/kubeadm-config.yaml" --upload-certs
  log_pass "kubeadm init completed."
fi

# --- kubeconfig for the vagrant user (guest-local convenience) ----------
install -d -m 0755 /home/vagrant/.kube
cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config
chown -R vagrant:vagrant /home/vagrant/.kube
chmod 600 /home/vagrant/.kube/config

# --- kubeconfig exported to the host via the shared /vagrant mount ------
# Never printed; permissions restricted; git-ignored (*kubeconfig*).
cp /etc/kubernetes/admin.conf "${GENERATED_DIR}/kubeconfig"
chmod 600 "${GENERATED_DIR}/kubeconfig"
log_pass "kubeconfig copied to .generated/kubeconfig (mode 600)."

export KUBECONFIG=/etc/kubernetes/admin.conf

wait_for "API server healthz" 90 3 -- kubectl get --raw='/healthz'

# --- Fresh worker join credentials (tokens expire ~24h; always regenerate) --
JOIN_COMMAND="$(kubeadm token create --print-join-command)"
KUBEADM_TOKEN="$(printf '%s' "${JOIN_COMMAND}" | grep -oP '(?<=--token )\S+')"
KUBEADM_CA_CERT_HASH="$(printf '%s' "${JOIN_COMMAND}" | grep -oP '(?<=--discovery-token-ca-cert-hash )\S+')"

{
  echo "#!/usr/bin/env bash"
  echo "# Generated by 05-init-control-plane.sh — do not commit, git-ignored."
  echo "${JOIN_COMMAND}"
} >"${GENERATED_DIR}/kubeadm-join-command.sh"
chmod 600 "${GENERATED_DIR}/kubeadm-join-command.sh"

{
  echo "CLUSTER_NAME=${CLUSTER_NAME}"
  echo "KUBEADM_TOKEN=${KUBEADM_TOKEN}"
  echo "KUBEADM_CA_CERT_HASH=${KUBEADM_CA_CERT_HASH}"
  echo "CONTROL_PLANE_ENDPOINT=${CONTROL_PLANE_ENDPOINT}"
} >"${GENERATED_DIR}/cluster-info.env"
chmod 600 "${GENERATED_DIR}/cluster-info.env"

log_pass "Worker join credentials (re)generated — token/hash written to .generated/cluster-info.env (not logged)."

log_info "Validation: node list -> $(kubectl get nodes -o wide --no-headers 2>/dev/null | wc -l) node(s) registered"
log_info "Validation: control-plane pods -> $(kubectl -n kube-system get pods -o wide --no-headers 2>/dev/null | grep -E 'kube-apiserver|etcd|kube-scheduler|kube-controller-manager' | awk '{print $1, $3}' | tr '\n' ' ')"

log_pass "05-init-control-plane complete for ${NODE_NAME}."
