#!/usr/bin/env bash
# Guest provisioning step 07: join a worker node to the cluster using
# fresh credentials generated by 05-init-control-plane.sh. Runs only on
# worker nodes. Idempotent: never re-attempts a join if this node is
# already registered.
set -euo pipefail

MODULE_ROOT="/vagrant"
# shellcheck source=../lib/common.sh
source "${MODULE_ROOT}/scripts/lib/common.sh"
# shellcheck source=../lib/validation.sh
source "${MODULE_ROOT}/scripts/lib/validation.sh"

require_root
: "${NODE_NAME:?}"
: "${NODE_ROLE:?}"
: "${NODE_IP:?}"

if [ "${NODE_ROLE}" != "worker" ]; then
  log_info "07-join-worker: not a worker, skipping (${NODE_NAME})."
  exit 0
fi

log_section "07-join-worker: kubeadm join (${NODE_NAME})"

if is_node_joined; then
  log_info "Node already joined (kubelet.conf present) — skipping 'kubeadm join'."
  log_pass "07-join-worker complete for ${NODE_NAME} (no-op, already joined)."
  exit 0
fi

CLUSTER_INFO_FILE="${GENERATED_DIR}/cluster-info.env"
if ! wait_for "control-plane join credentials (.generated/cluster-info.env)" 300 5 -- test -s "${CLUSTER_INFO_FILE}"; then
  log_fatal "Control-plane join credentials never appeared. Was 'vagrant up ${CONTROL_PLANE_NAME}' run and completed successfully first? See docs/TROUBLESHOOTING.md 'Worker join token expired'."
fi
# shellcheck source=/dev/null
source "${CLUSTER_INFO_FILE}"
: "${KUBEADM_TOKEN:?cluster-info.env did not contain KUBEADM_TOKEN}"
: "${KUBEADM_CA_CERT_HASH:?cluster-info.env did not contain KUBEADM_CA_CERT_HASH}"

export NODE_NAME NODE_IP CRI_SOCKET CONTROL_PLANE_ENDPOINT KUBEADM_TOKEN KUBEADM_CA_CERT_HASH
render_template "${MODULE_ROOT}/config/kubeadm-join-config.yaml.tpl" "${RENDERED_DIR}/kubeadm-join-config-${NODE_NAME}.yaml"

if ! kubeadm join --config "${RENDERED_DIR}/kubeadm-join-config-${NODE_NAME}.yaml"; then
  log_fail "kubeadm join failed for ${NODE_NAME}."
  log_info "If the token expired, re-run 'make setup' (or 'vagrant provision ${CONTROL_PLANE_NAME}') to regenerate .generated/cluster-info.env, then re-provision this worker."
  exit 1
fi

log_pass "kubeadm join succeeded for ${NODE_NAME}."
log_pass "07-join-worker complete for ${NODE_NAME}."
