apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: otel-demo
  labels:
    app.kubernetes.io/part-of: observability-learning-lab
spec:
  type: ClusterIP
  selector: {app: inventory-service}
  ports:
    - {name: http, port: 8000, targetPort: http}
